
<html>
<head>
<title>hospital</title>
</head>
<body>
<body background="https://images.app.goo.gl/M8aBpf18ThxBkuEw8">
<h1><font size="30" color="BLACK"><center><b><u>BHM HOSPITAL</u></b></center></font></h1>
<h2><font size="11" color="blue" face="segoe print">Overview</font></h2>
<p><font size="5" color="grey" face="MV Boli"> Youheal set in a soothingly beautiful 40-acre waterfront campus, is a 670-bed quaternary care facility & one of the best hospital in Kochi, Kerala.
Across the years, Youheal has evolved into a medical destination - one that attracts not just thousands of patients across the world;
 but also attracts and nurtures the best talent, keeps upgrading technology as well as fosters research, education and a distinctive work culture that is ethically and socially relevant.
<br><br><br>
<img src="youheal.jpg"  height="350" width="550">
<h2><font size="7" color="purple">Youheal Centres of Excellence</font></h2>
<p><font size="5" color="olive" face="tahoma">Youheal's Centres of Excellence (COE) are an amalgamation of experienced doctors, state of the art technology, and the highest level of patient care and treatment.
<br> Our COE's ensure that every aspect of your care is seamless and the team of experts work together to provide the care you need.
<ul type="square">
<li>Cardiology</li>
<li>Gynacology</li>
<li>Orthopaedics</li>
<li>Neuorology</li>
<li>Pediatrics</li>
</ul>
<h2><font size="9" color="purple" face="Bodoni MT">Our Doctors</font></h2>
<img src="cardiac.jpg" height="140" width="150">
<br><font size="5" color="black" face="century">Dr Arun Raj,Senior Cardiologist<br>MBBS,MD</font>
<body link="blue" vlink="red" alink="purple">
<br>
<A Href="youhealform.html">Click to book an appoinment</a>
<br><br>
<img src="gynac.jpg" height="140" width="150">
<br><font size="5" color="black" face="century">Dr Greeshma Sara,Gynacologist<br>MBBS,DGO,DNB</font>
<br>
<body link="blue" vlink="red" alink="purple">
<A Href="youhealform.html">Click to book an appoinment</a>
<marquee><p><font size="3" color="purple" face="century" align="center">Thank you for visiting</font></p></marquee>
</body> 
</html>
